// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Testing2.Services;

namespace Testing2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210130184930_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Testing2.Telemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("StoreRequestFinished")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StoreRequestStarted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TelemetryNumber")
                        .HasColumnType("text");

                    b.Property<bool>("successful")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("timeOfRequest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("webRequestRecieved")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("webRequestSent")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
